type uToken = { kind : uTokenKind; charIdx : int; lineIdx : int; colIdx : int }
[@@deriving show { with_path = false }]

and uTokenKind =
  (* Reserved *)
  | AS (* as *)
  | AND (* and *)
  | BREAK (* break *)
  | CONTINUE (* continue *)
  | ELSE (* else *)
  | FALSE (* false *)
  | FLOAT (* float *)
  | FUNCTION (* fn *)
  | IF (* if *)
  | INT (* int *)
  | LET (* let *)
  | MATCH (* match *)
  | MOD (* mod *)
  | MUT (* mut *)
  | NOT (* not ! *)
  | OR (* or *)
  | PUBLIC (* pub *)
  | RETURN (* return *)
  | UNDEFINED (* undefined *)
  | USE (* use *)
  (* Mathematical *)
  | PLUS (* + *)
  | MINUS (* - *)
  | STAR (* * *)
  | SLASH (* / *)
  (* Conditionals *)
  | EQEQ (* == *)
  | EQ (* = *)
  | GE (* >= *)
  | LE (* <= *)
  | GT (* > *)
  | LT (* < *)
  (* Symbols *)
  | SEMICOLON (* ; *)
  | QUESTION (* ? *)
  | AMPERSAND (* & *)
  | COLON (* : *)
  | COMMA (* , *)
  | DOTDOT (* .. *)
  | DOT (* . *)
  | BAR (* | *)
  | LPAREN (* ( *)
  | RPAREN (* ) *)
  | LBRACE (* { *)
  | RBRACE (* } *)
  | LBRACK (* [ *)
  | RBRACK (* ] *)
  (* Values *)
  | NAMEVAL of string
  | INTVAL
  (* Other *)
  | WHITESPACE (* ' ' '\t' *)
  | NEWLINE (* '\n' *)
  | DOCUMENT (* /// *)
  | COMMENT (* // *)
  | EOF
